name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  parameter:
    description: 'An input parameter'
    default: 'example'
outputs:
  result:
    description: "Result of the action"
runs:
  using: 'docker'
  image: 'Dockerfile'
